language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

dist: trusty

branches:
  only:
    - master

git:
  depth: 5

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
  - nightly

  allow_failures:
    - php: nightly

before_script:
  - export PATH="./vendor/bin:$PATH"
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
  - phpmd src,tests text ./phpmd.xml
  - phpunit

after_success:
 - bash <(curl -s https://codecov.io/bash)
