language: php

sudo: false

dist: trusty

branches:
  only:
    - master

git:
  depth: 5

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: PHPCS=PSR2

  allow_failures:
    - php: nightly

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install -n
  - composer self-update
  - composer install

script:
  - php vendor/bin/phpunit
  - |
    if [[ "$PHPCS" ]] ; then
      vendor/bin/phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
    fi
  
after_script:
  - php vendor/bin/codacycoverage clover path/to/clover.xml